// The rooms' anchor furniture, c. 1660 (design/house/r47-plan.md §5): the piece that names each room,
// from the inventories (design/house/program-1660-research.md, cited R §2). Data only, over the shape
// parts and the joinery parts. Everything that obviously works, works: bed curtains draw back, cupboard and
// press doors open, lids lift, a gateleg's leaves rise, a draw-table's leaves slide out, a hogshead's tap
// is turned, the kitchen's spit goes round while the jack runs. Frame: back at z = 0 against a wall, front
// toward +z, centred on x = 0, standing on y = 0. "=expr" is arithmetic over the settings. How a piece
// stands in its room (src/make/furnish.js) is a trait: "free" in the middle, "beside" the free table,
// "hearth" in the fire's mouth, "wall" hung; otherwise back to a wall.
const P = Math.PI;
const LEG = [[0, 0], [0.024, 0], [0.026, 0.06], [0.02, 0.1], [0.028, 0.2], [0.034, 0.3], [0.022, 0.38], [0.018, 0.42], [0.024, 0.48]];   // a turned leg to 0.48 m, scaled by ops
const legs = (role, hExpr, inset, w, d) => [-1, 1].flatMap(sx => [-1, 1].map(sz => ({ part: "lathe", role, segments: 12, profile: LEG, ops: [["s", 1, `=(${hExpr})/0.48`, 1], ["t", `=${sx}*(${w}/2-${inset})`, 0, `=${d}/2+${sz}*(${d}/2-${inset})`]] })));
export default [
  // ---- the hall: a long table and forms (Worden 1643: a table 8 yards long; forms)
  { kind: "table/long-hall", v: 1, noun: "the long table", fixed: true, traits: ["free"], why: "R §2: the hall's long table (Worden 1643), joined oak, no drawer",
    settings: { W: 3.6, D: 0.85, H: 0.78 }, parts: [{ part: "joined_table", drawer: false }] },
  { kind: "form/joined", v: 1, noun: "the form", fixed: true, traits: ["beside"], why: "R §2: forms by the long table (Middleton parlour 1618: 2 long forms)",
    size: ["$W", "$H", "$D"], settings: { W: 2.4, H: 0.46, D: 0.3 },
    parts: [{ part: "box", role: "wood_face", size: ["$W", 0.04, "$D"], at: [0, "=H-0.04", "=D/2"] }, ...legs("wood", "H-0.04", 0.12, "W", "D"),
      { part: "box", role: "wood", size: ["=W-0.2", 0.03, 0.03], at: [0, 0.08, "=D/2"] }] },
  { kind: "table/kitchen", v: 1, noun: "the kitchen table", fixed: true, traits: ["free"], why: "R §2: the kitchen's working table, scrubbed deal or oak",
    settings: { W: 2.2, D: 0.8, H: 0.8 }, parts: [{ part: "joined_table", drawer: false }] },
  // ---- the parlours: a court cupboard, Turkey-work chairs, a gateleg table (Bank Hall c.1670; Middleton 1618)
  { kind: "cupboard/court", v: 1, noun: "the court cupboard", fixed: true, why: "R §2: a court cupboard with its cloth (Bank Hall 1632; Oakwell): a closed lower stage with doors, an open upper stage under a canopy on bulbous posts",
    settings: { W: 1.2, D: 0.5, H: 1.3 },
    parts: [
      { part: "box", role: "wood", size: ["$W", 0.62, "$D"], at: [0, 0.06, "=D/2"] },
      { part: "box", role: "wood_face", size: ["=W+0.04", 0.04, "=D+0.03"], at: [0, 0.68, "=D/2"] },
      { part: "box", role: "wood", size: ["=W-0.04", 0.3, "=D*0.6"], at: [0, 0.72, "=D*0.3"] },
      { part: "box", role: "wood_face", size: ["=W+0.06", 0.06, "=D+0.04"], at: [0, "=H-0.06", "=D/2"] },
      { part: "lathe", role: "wood_face", segments: 14, profile: [[0, 0], [0.025, 0], [0.025, 0.08], [0.07, 0.24], [0.06, 0.34], [0.025, 0.42], [0.025, 0.56], [0, 0.56]], ops: [["t", "=-W/2+0.05", 0.72, "=D-0.05"]] },
      { part: "lathe", role: "wood_face", segments: 14, profile: [[0, 0], [0.025, 0], [0.025, 0.08], [0.07, 0.24], [0.06, 0.34], [0.025, 0.42], [0.025, 0.56], [0, 0.56]], ops: [["t", "=W/2-0.05", 0.72, "=D-0.05"]] },
      { part: "box", role: "linen", size: ["=W+0.02", 0.004, "=D+0.06"], at: [0, 0.721, "=D/2"] },
      { part: "mover", name: "left", pivot: ["=-W/2+0.04", 0, "$D"] }, { part: "mover", name: "right", pivot: ["=W/2-0.04", 0, "$D"] },
      { part: "box", role: "wood_face", mover: "left", size: ["=W/2-0.05", 0.5, 0.025], at: ["=-W/4+0.005", 0.12, "=D+0.013"] },
      { part: "box", role: "wood_face", mover: "right", size: ["=W/2-0.05", 0.5, 0.025], at: ["=W/4-0.005", 0.12, "=D+0.013"] }],
    affordances: {
      left: { mover: "left", motion: "hinge", axis: [0, 1, 0], angle: -1.7, verbs: ["open the cupboard door", "close the cupboard door"] },
      right: { mover: "right", motion: "hinge", axis: [0, 1, 0], angle: 1.7, verbs: ["open the cupboard door", "close the cupboard door"] } } },
  { kind: "chair/turkey-work", v: 1, noun: "the chair", fixed: false, why: "R §2: Turkey-work chairs (Bank Hall dining room c.1670: 24 Turkey-work chairs and stools)",
    size: [0.5, 1.05, 0.5], settings: {},
    parts: [...legs("wood", "0.44", 0.04, "0.48", "0.46"),
      { part: "box", role: "turkey", size: [0.5, 0.07, 0.48], at: [0, 0.44, 0.24] },
      { part: "box", role: "wood", size: [0.04, 0.6, 0.04], at: [-0.22, 0.44, 0.03] }, { part: "box", role: "wood", size: [0.04, 0.6, 0.04], at: [0.22, 0.44, 0.03] },
      { part: "box", role: "turkey", size: [0.4, 0.36, 0.04], at: [0, 0.62, 0.03] }] },
  { kind: "chair/joined", v: 1, noun: "the chair", fixed: false, why: "a joined oak back stool, the living parlour's chair",
    size: [0.48, 1.0, 0.46], settings: {},
    parts: [...legs("wood", "0.44", 0.04, "0.46", "0.44"),
      { part: "box", role: "wood_face", size: [0.48, 0.04, 0.46], at: [0, 0.44, 0.23] },
      { part: "box", role: "wood", size: [0.04, 0.56, 0.04], at: [-0.21, 0.44, 0.03] }, { part: "box", role: "wood", size: [0.04, 0.56, 0.04], at: [0.21, 0.44, 0.03] },
      { part: "box", role: "wood_face", size: [0.38, 0.22, 0.025], at: [0, 0.7, 0.03] }] },
  { kind: "table/gateleg", v: 1, noun: "the gateleg table", fixed: true, why: "a gateleg table against the wall: its leaf hangs down until a gate swings out to hold it up",
    settings: { W: 1.1, D: 0.4, H: 0.74, leaf: 0.42 },
    parts: [...legs("wood", "H-0.03", 0.05, "W", "D"),
      { part: "box", role: "wood_face", size: ["$W", 0.03, "$D"], at: [0, "=H-0.03", "=D/2"] },
      { part: "box", role: "wood", size: [0.04, 0.04, "=D-0.1"], at: [0, 0.06, "=D/2"] },
      { part: "box", role: "wood", size: [0.04, "=H-0.14", 0.04], at: [0, 0.06, "=D-0.05"] },
      { part: "mover", name: "front", pivot: [0, "=H-0.015", "$D"] },
      { part: "box", role: "wood_face", mover: "front", size: ["$W", "$leaf", 0.025], at: [0, "=H-0.015-leaf", "=D+0.0125"] },
      // the gate: an upright pivoting on the frame, a rail and a stretcher out to a turned leg; it folds flat against the frame
      { part: "mover", name: "gate", pivot: [0, 0, "=D-0.05"] },
      { part: "lathe", role: "wood", mover: "gate", segments: 12, profile: LEG, ops: [["s", 1, "=(H-0.04)/0.48", 1], ["t", "=-(leaf-0.08)", 0, "=D-0.05"]] },
      { part: "box", role: "wood", mover: "gate", size: ["=leaf-0.08", 0.04, 0.03], at: ["=-(leaf-0.08)/2", "=H-0.12", "=D-0.05"] },
      { part: "box", role: "wood", mover: "gate", size: ["=leaf-0.08", 0.03, 0.03], at: ["=-(leaf-0.08)/2", 0.08, "=D-0.05"] }],
    // raising the leaf swings the gate out first; the gate won't fold while the leaf rests on it
    affordances: {
      gate: { mover: "gate", motion: "hinge", axis: [0, 1, 0], angle: 1.5708, auto: true, done: "the gate swings out under it", release: { front: "down" }, held: "the leaf rests on it", verbs: ["swing out the gate", "fold the gate"] },
      front: { mover: "front", motion: "hinge", axis: [1, 0, 0], angle: -1.5708, states: ["down", "up"], requires: { gate: "open" }, refused: "nothing would hold it up", verbs: ["raise the leaf", "let the leaf down"] } } },
  // ---- the study and the great chamber: a draw-table whose leaves slide out (Rufford dining chamber 1620: a drawing table)
  { kind: "table/drawing", v: 1, noun: "the draw-table", fixed: true, traits: ["free"], why: "R §2: a drawing table (Rufford dining chamber 1620): leaves under the top draw out at each end",
    settings: { W: 2.0, D: 0.85, H: 0.78 },
    parts: [{ part: "joined_table", drawer: false },
      { part: "mover", name: "west", pivot: [0, 0, 0] }, { part: "mover", name: "east", pivot: [0, 0, 0] },
      { part: "box", role: "wood_face", mover: "west", size: [0.6, 0.028, "=D-0.06"], at: ["=-W/2+0.33", "=H-0.065", "=D/2+0.01"] },
      { part: "box", role: "wood_face", mover: "east", size: [0.6, 0.028, "=D-0.06"], at: ["=W/2-0.33", "=H-0.065", "=D/2+0.01"] }],
    // each leaf runs out on its bearers and rises the last few centimetres to lie level with the top
    affordances: {
      west: { mover: "west", motion: "slide", axis: [-1, 0.062, 0], travel: 0.6, verbs: ["draw out the leaf", "push the leaf home"] },
      east: { mover: "east", motion: "slide", axis: [1, 0.062, 0], travel: 0.6, verbs: ["draw out the leaf", "push the leaf home"] } } },
  { kind: "cupboard/press", v: 1, noun: "the press cupboard", fixed: true, why: "R §2: cupboards in the pantry (Hardwick 1601): a tall joined press, two doors, shelves within",
    settings: { W: 1.3, D: 0.55, H: 1.9 },
    parts: [{ part: "box", role: "wood", size: ["$W", "$H", 0.03], at: [0, 0, 0.015] },
      { part: "box", role: "wood", size: [0.04, "$H", "$D"], at: ["=-W/2+0.02", 0, "=D/2"] }, { part: "box", role: "wood", size: [0.04, "$H", "$D"], at: ["=W/2-0.02", 0, "=D/2"] },
      { part: "box", role: "wood_face", size: ["=W+0.04", 0.05, "=D+0.03"], at: [0, "$H", "=D/2"] }, { part: "box", role: "wood", size: ["$W", 0.06, "$D"], at: [0, 0, "=D/2"] },
      { part: "box", role: "wood_inside", size: ["=W-0.08", 0.025, "=D-0.06"], at: [0, 0.65, "=D/2"] }, { part: "box", role: "wood_inside", size: ["=W-0.08", 0.025, "=D-0.06"], at: [0, 1.2, "=D/2"] },
      { part: "mover", name: "left", pivot: ["=-W/2+0.02", 0, "$D"] }, { part: "mover", name: "right", pivot: ["=W/2-0.02", 0, "$D"] },
      { part: "box", role: "wood_face", mover: "left", size: ["=W/2-0.03", "=H-0.1", 0.025], at: ["=-W/4+0.005", 0.07, "=D+0.013"] },
      { part: "box", role: "wood_face", mover: "right", size: ["=W/2-0.03", "=H-0.1", 0.025], at: ["=W/4-0.005", 0.07, "=D+0.013"] }],
    affordances: {
      left: { mover: "left", motion: "hinge", axis: [0, 1, 0], angle: -1.7, verbs: ["open the press", "close the press"] },
      right: { mover: "right", motion: "hinge", axis: [0, 1, 0], angle: 1.7, verbs: ["open the press", "close the press"] } } },
  // ---- service: a hogshead on its stand with a tap; a powdering tub; the kitchen's jack and spit
  { kind: "barrel/hogshead-on-stand", v: 1, noun: "the hogshead", fixed: true, why: "R §2: hogsheads on stands with iron hoops (Dunkenhalgh 1679: 'two stands, four iron hoopes with screws for hogsheads')",
    settings: { L: 0.95, R: 0.36 },
    parts: [{ part: "box", role: "wood", size: [0.8, 0.26, 0.12], at: [0, 0, "=L*0.22+0.05"] }, { part: "box", role: "wood", size: [0.8, 0.26, 0.12], at: [0, 0, "=L*0.78+0.05"] },
      { part: "lathe", role: "wood_face", segments: 20, profile: [[0, 0], ["=R*0.85", 0], ["=R", "=L/2"], ["=R*0.85", "$L"], [0, "$L"]], ops: [["t", 0, "=-L/2", 0], ["rx", P / 2], ["t", 0, "=0.26+R", "=L/2+0.05"]] },
      { part: "torus", role: "iron", r: "=R*0.95", tube: 0.008, radial: 4, tubular: 24, at: [0, "=0.26+R", "=L*0.2+0.05"] },
      { part: "torus", role: "iron", r: "=R*0.95", tube: 0.008, radial: 4, tubular: 24, at: [0, "=0.26+R", "=L*0.8+0.05"] },
      { part: "cylinder", role: "wood", r: 0.014, h: 0.1, segments: 8, ops: [["rx", P / 2], ["t", 0, "=0.26+R*0.45", "=L+0.03"]] },
      { part: "mover", name: "tap", pivot: [0, "=0.26+R*0.45", "=L+0.1"] },
      { part: "box", role: "iron", mover: "tap", size: [0.07, 0.016, 0.014], at: [0, "=0.26+R*0.45+0.012", "=L+0.1"] }],
    affordances: { tap: { mover: "tap", motion: "lever", axis: [0, 0, 1], angle: 1.5708, verbs: ["turn the tap", "turn the tap off"] } } },
  { kind: "tub/powdering", v: 1, noun: "the powdering tub", fixed: true, why: "R §2: powdering tubs for salting meat (Dunkenhalgh: 3 large powdering tubs)",
    settings: { R: 0.32, H: 0.6 },
    parts: [{ part: "lathe", role: "wood_face", segments: 20, profile: [[0, 0], ["=R*0.85", 0], ["$R", "$H"], [0, "$H"]], at: [0, 0, 0.35] },
      { part: "torus", role: "iron", r: "=R*0.9", tube: 0.007, radial: 4, tubular: 24, ops: [["rx", P / 2], ["t", 0, "=H*0.25", 0.35]] },
      { part: "torus", role: "iron", r: "=R*0.98", tube: 0.007, radial: 4, tubular: 24, ops: [["rx", P / 2], ["t", 0, "=H*0.8", 0.35]] },
      { part: "mover", name: "lid", pivot: [0, "$H", 0.35] },
      { part: "cylinder", role: "wood", mover: "lid", r: "=R+0.01", h: 0.03, segments: 20, at: [0, "$H", 0.35] }],
    affordances: { lid: { mover: "lid", motion: "slide", axis: [1, 0.12, 0], travel: 0.4, verbs: ["push the lid aside", "put the lid back"] } } },
  { kind: "hearth/kitchen-jack", v: 1, noun: "the spit", fixed: true, traits: ["hearth"], why: "R §2: the kitchen's jack with its weight and chains, spits, racks (Dunkenhalgh 1679); a spit turned by a jack",
    settings: { W: 2.4 },
    parts: [{ part: "box", role: "iron", size: [0.06, 0.55, 0.06], at: ["=-W/2+0.2", 0, 0.45] }, { part: "box", role: "iron", size: [0.06, 0.55, 0.06], at: ["=W/2-0.2", 0, 0.45] },
      { part: "mover", name: "spit", pivot: [0, 0.5, 0.45] },
      { part: "cylinder", role: "iron", mover: "spit", r: 0.012, h: "=W-0.2", segments: 8, ops: [["t", 0, "=-(W-0.2)/2", 0], ["rz", P / 2], ["t", 0, 0.5, 0.45]] },
      { part: "box", role: "iron", mover: "spit", size: [0.16, 0.16, 0.16], at: [0, 0.42, 0.45] },
      { part: "spinner", mover: "spit", axis: [1, 0, 0], rate: 1.6, when: "jack" }],
    affordances: { jack: { hit: "body", motion: "state", states: ["still", "turning"], verbs: ["wind the jack", "stop the jack"] } } },
  // ---- chambers: the standing bed with its curtains (Bank Hall Egle Chamber 1632: 'standing bed … 5 silk curtains with rods'), a close stool, a chest
  { kind: "bed/standing-curtained", v: 1, noun: "the bed", fixed: true, why: "R §2: a standing bed with valance and curtains on rods (Bank Hall 1632); a truckle bed beneath (Ashmore)",
    settings: { W: 1.6, L: 2.0, H: 2.3 },
    parts: [
      ...[-1, 1].flatMap(sx => [0, 1].map(sz => ({ part: "lathe", role: "wood_face", segments: 12, profile: [[0, 0], [0.05, 0], [0.05, 0.5], [0.035, 0.6], [0.05, 0.9], [0.03, 1.2], [0.04, 1.6], [0.03, 2.0], [0.03, "$H"], [0, "$H"]], ops: [["t", `=${sx}*(W/2-0.05)`, 0, `=${sz}*(L-0.1)+0.05`]] }))),
      { part: "box", role: "wood", size: ["=W-0.1", 0.3, "=L-0.1"], at: [0, 0.25, "=L/2"] },
      { part: "box", role: "linen", size: ["=W-0.12", 0.22, "=L-0.15"], at: [0, 0.55, "=L/2+0.02"] },
      { part: "box", role: "hangings", size: ["=W-0.1", 0.06, "=L-0.25"], at: [0, 0.77, "=L/2+0.08"] },
      { part: "box", role: "wood_face", size: ["=W-0.1", 1.1, 0.05], at: [0, 0.55, 0.05] },
      { part: "box", role: "hangings", size: ["=W+0.04", 0.35, "=L+0.04"], at: [0, "=H-0.35", "=L/2"] },
      { part: "box", role: "wood_face", size: ["=W+0.06", 0.06, "=L+0.06"], at: [0, "=H", "=L/2"] },
      { part: "box", role: "hangings", size: [0.03, "=H-0.75", 0.3], at: ["=-W/2+0.05", 0.45, 0.25] }, { part: "box", role: "hangings", size: [0.03, "=H-0.75", 0.3], at: ["=W/2-0.05", 0.45, 0.25] },
      { part: "mover", name: "left", pivot: ["=-W/2+0.05", 0, "=L-0.02"] }, { part: "mover", name: "right", pivot: ["=W/2-0.05", 0, "=L-0.02"] },
      { part: "box", role: "hangings", mover: "left", size: ["=W/2-0.02", "=H-0.75", 0.02], at: ["=-W/4", 0.45, "=L-0.02"] },
      { part: "box", role: "hangings", mover: "right", size: ["=W/2-0.02", "=H-0.75", 0.02], at: ["=W/4", 0.45, "=L-0.02"] }],
    affordances: {
      // a curtain drawn back folds round its foot post to hang along the bed's side
      left: { mover: "left", motion: "hinge", axis: [0, 1, 0], angle: 1.5, initial: "open", verbs: ["draw back the curtain", "draw the curtain"] },
      right: { mover: "right", motion: "hinge", axis: [0, 1, 0], angle: -1.5, initial: "open", verbs: ["draw back the curtain", "draw the curtain"] } } },
  { kind: "bed/truckle", v: 1, noun: "the truckle bed", fixed: true, why: "R §2: truckle beds and chaff beds for servants (Ashmore pp.66-67)",
    settings: { W: 0.9, L: 1.85 },
    parts: [{ part: "box", role: "wood", size: ["$W", 0.22, "$L"], at: [0, 0.04, "=L/2"] }, { part: "box", role: "linen", size: ["=W-0.06", 0.12, "=L-0.06"], at: [0, 0.26, "=L/2"] }] },
  { kind: "stool/close", v: 1, noun: "the close stool", fixed: false, why: "R §2: close stools with pans, often in the closet (Dunkenhalgh: 4 of 7 in closets)",
    size: [0.46, 0.5, 0.4], settings: {},
    parts: [{ part: "box", role: "wood_face", size: [0.46, 0.44, 0.4], at: [0, 0, 0.2] },
      { part: "mover", name: "lid", pivot: [0, 0.44, 0] }, { part: "box", role: "wood_face", mover: "lid", size: [0.48, 0.03, 0.42], at: [0, 0.44, 0.2] }],
    affordances: { lid: { mover: "lid", motion: "hinge", axis: [1, 0, 0], angle: -1.6, verbs: ["lift the lid", "close the lid"] } } },
  { kind: "chest/boarded", v: 1, noun: "the chest", fixed: true, why: "a boarded oak chest at the bed's foot: linen and clothes",
    settings: { w: 1.1, d: 0.5, h: 0.6 }, parts: [{ part: "boarded_box" }],
    affordances: { lid: { mover: "lid", motion: "hinge", axis: [1, 0, 0], angle: -1.65, verbs: ["open the chest", "close the chest"] } } },
  // ---- the closet: a japanned cabinet on its stand (Ham's Green Closet: 2 Japan cabinets)
  { kind: "cabinet/japanned", v: 1, noun: "the cabinet", fixed: true, why: "R §2: Japan cabinets in the closet (Ham, Green Closet); doors before small drawers",
    settings: { W: 0.9, D: 0.45 },
    parts: [...legs("japan", "0.7", 0.05, "W", "D"), { part: "box", role: "japan", size: ["$W", 0.04, "$D"], at: [0, 0.7, "=D/2"] },
      { part: "box", role: "japan", size: ["=W-0.04", 0.6, "=D-0.04"], at: [0, 0.74, "=D/2-0.02"] },
      { part: "box", role: "gilt", size: ["=W-0.12", 0.5, 0.005], at: [0, 0.79, "=D-0.039"] },
      { part: "mover", name: "left", pivot: ["=-W/2+0.02", 0, "=D-0.04"] }, { part: "mover", name: "right", pivot: ["=W/2-0.02", 0, "=D-0.04"] },
      { part: "box", role: "japan", mover: "left", size: ["=W/2-0.03", 0.58, 0.02], at: ["=-W/4", 0.75, "=D-0.03"] },
      { part: "box", role: "japan", mover: "right", size: ["=W/2-0.03", 0.58, 0.02], at: ["=W/4", 0.75, "=D-0.03"] },
      { part: "box", role: "gilt", mover: "left", size: ["=W/2-0.1", 0.46, 0.004], at: ["=-W/4", 0.81, "=D-0.019"] },
      { part: "box", role: "gilt", mover: "right", size: ["=W/2-0.1", 0.46, 0.004], at: ["=W/4", 0.81, "=D-0.019"] }],
    affordances: {
      left: { mover: "left", motion: "hinge", axis: [0, 1, 0], angle: -1.8, verbs: ["open the cabinet", "close the cabinet"] },
      right: { mover: "right", motion: "hinge", axis: [0, 1, 0], angle: 1.8, verbs: ["open the cabinet", "close the cabinet"] } } },
  // ---- the nursery and the gallery
  { kind: "chair/child", v: 1, noun: "the child's chair", fixed: false, why: "R §2: a child's chair (Middleton 1618)",
    size: [0.34, 0.65, 0.32], settings: {},
    parts: [...legs("wood", "0.28", 0.03, "0.32", "0.3"), { part: "box", role: "wood_face", size: [0.34, 0.03, 0.32], at: [0, 0.28, 0.16] },
      { part: "box", role: "wood_face", size: [0.3, 0.3, 0.02], at: [0, 0.31, 0.02] }] },
  { kind: "picture/portrait", v: 1, noun: "the portrait", fixed: true, why: "R §2: portraits down the long gallery (Dunkenhalgh: 15 pictures; Rufford: 29)", traits: ["wall"],
    settings: { W: 0.75, H: 0.95, at_y: 1.25 },
    parts: [{ part: "box", role: "gilt", size: ["=W+0.12", "=H+0.12", 0.05], at: [0, "=at_y-0.06", 0.025] }, { part: "box", role: "canvas", size: ["$W", "$H", 0.012], at: [0, "$at_y", 0.05] }] },
  // ---- the bakehouse: the bread oven with its iron door, the kneading trough with its lid
  { kind: "oven/bread", v: 1, noun: "the bread oven", fixed: true, why: "R §1.2: the bakehouse's oven (Ashmore): a brick dome with an iron door",
    settings: { R: 0.8 },
    parts: [{ part: "box", role: "brick", size: [1.9, 0.9, 1.8], at: [0, 0, 0.9] },
      { part: "sphere", role: "brick", r: "$R", w: 20, h: 10, theta_len: P / 2, at: [0, 0.9, 0.9] },
      { part: "mover", name: "door", pivot: [-0.22, 0, 1.81] },
      { part: "box", role: "iron", mover: "door", size: [0.44, 0.34, 0.03], at: [0, 0.4, 1.81] }],
    affordances: { door: { mover: "door", motion: "hinge", axis: [0, 1, 0], angle: -1.6, verbs: ["open the oven", "close the oven"] } } },
  { kind: "trough/kneading", v: 1, noun: "the kneading trough", fixed: true, why: "the bakehouse's kneading trough on legs, its lid a board to work on",
    settings: { W: 1.4, D: 0.55 },
    parts: [...legs("wood", "0.55", 0.06, "W", "D"), { part: "box", role: "wood", size: ["$W", 0.3, "$D"], at: [0, 0.55, "=D/2"] },
      { part: "mover", name: "lid", pivot: [0, 0.85, 0] }, { part: "box", role: "wood_face", mover: "lid", size: ["=W+0.03", 0.03, "=D+0.03"], at: [0, 0.85, "=D/2"] }],
    affordances: { lid: { mover: "lid", motion: "hinge", axis: [1, 0, 0], angle: -1.6, verbs: ["lift the lid", "close the lid"] } } },
];
