#!/usr/bin/env python3
"""Every artifact this pipeline DERIVES, what invalidates it, and how it is remade.

    python3 design/plan-draft/measured/derived.py --check
    python3 design/plan-draft/measured/derived.py --check --json
    python3 design/plan-draft/measured/derived.py --check --deep
    python3 design/plan-draft/measured/derived.py --regen [--only <id>]

    python3 design/plan-draft/measured/row23_run.py --derive-check   # the same check

WHY THIS FILE EXISTS. [production law clause 6] "Your solutions need to fold
into the generation method for future builds" — a correction lands in the
EMITTER, a GATE or the INSTRUMENT, never in a hand-retouched artifact.

Eight suite cases were red on `main` whenever the manor loop had run and green
on a frozen tree, and every one of them compared a COMMITTED GENERATED ARTIFACT
against a live store that had moved under it. The loop promotes a wall,
supersedes a wall, re-snaps a frame or paints a door void — and the artifacts
those acts invalidate were regenerated by whichever command the Navigator
happened to type next. So the ledger tick shipped stale derived files, and the
suite read that as breakage. The defect is not in any of the eight cases and
not in any of the artifacts: it is that nothing in the machine knew WHICH
ARTIFACT EACH ACT INVALIDATES. This file is that knowledge, in one place.

    THE TABLE — artifact -> what invalidates it

    material_provenance.json     any promotion or supersede (the ask a painting
                                 was made from is read off the store), any edit
                                 to the voice table or the composer
    material_legacy.json         the same: the ledger admits one facing from one
                                 exact candidate, so a re-ask closes a line
    room_consistency.json        any promotion or supersede in a measured room
    row40-consistency/README.md  the same (its hand-written tail is kept)
    window_calibration.json      any promotion or supersede (it is the list of
                                 promoted walls the window clause cannot see)
    row35snap/<loc>-<F>.json     a re-snap: the frame a reading describes is
      + its snapped.png          rewritten under the reading that describes it
    row36doors/<loc>-<F>.json    a re-repair, or a change to the snapped frame
      + its doored.png           the voids were painted onto
    manor/retries.json           a neighbour's RE-PROMOTION: an edge strip was
      (edge_seed records)        cut from a painting the store has replaced
    backdrops/<loc>/<F>.meta     the candidate it names, and the reading that
      + <F>.png                  candidate was measured in
    backdrops/baked.js           any promotion (the picture the page renders)
    fixtures/*/fixture.js        any promotion (the meta the page renders with)

TWO MODES, AND THE FAST ONE IS THE ONE THE GUARDS SHARE.

  `--check`  asks every artifact whether it is stale WITHOUT WRITING ANYTHING.
             It is what `tools/publish-site.sh` refuses on and what the suite's
             own freshness helper reads, so the publish preflight and the
             tests cannot disagree about what fresh means. Two kinds of answer
             stand behind it: a WITNESS the artifact carries itself (a reading
             records the digest of the frame it describes — nothing has to be
             regenerated to know it has gone stale) and, where an artifact
             carries no witness, the digest of its INPUT SET recorded in
             `derived-state.json` when it was last derived. An input digest
             includes the GENERATOR'S OWN SOURCE, because a change to the
             instrument stales its output exactly as a change to the store does.

  `--deep`   regenerates into a temporary tree and compares BYTE FOR BYTE. It is
             the honest answer and it costs about half a minute; it exists so
             that the fast answer is a claim that can be checked rather than one
             that has to be believed. `--check --deep` runs both and reports a
             disagreement between them as a finding of its own.

IDEMPOTENT, AND IT SAYS SO. `--regen` runs only the actions whose artifacts the
check calls stale, writes only files whose bytes actually move, and prints what
it did and did not do. A second run regenerates nothing and says `nothing to
regenerate`. Every action is clocked into the row-33 ledger as `derive.regen`,
one record per artifact, with what it wrote.

WHAT THIS FILE WILL NOT DO. It never decides which candidate a wall ships — that
is the sweep's, and it is made of measurements. When a reading and the frame it
describes disagree, the reading is the record of a measurement that was taken
and the frame is a picture that can be recomputed from it, so the FRAME is
re-derived from the candidate the reading names. If that reproduces different
bytes, the pair is refused with the reason rather than quietly rewritten.
"""
import argparse
import glob
import hashlib
import json
import os
import shutil
import subprocess
import sys
import tempfile
import time

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

import timings  # noqa: E402

MANOR = os.path.join(ROOT, "design", "batches", "row23-scaffold", "manor")
RETRIES_FILE = os.path.join(MANOR, "retries.json")
PLAN = os.path.join(ROOT, "fixtures", "demo-study", "plan.json")
SNAP_ROUND, DOOR_ROUND = "row35snap", "row36doors"


def snap_frame(loc, fac):
    """Where a wall's snapped frame lives — `row23_run.SNAP_SOURCE_DIR`'s rule.

    A function rather than a constant because everything here is addressed
    relative to ROOT, and a path frozen at import time is a path that stops
    meaning what it says the moment ROOT is anything but this checkout — which
    `test_derived.py` does deliberately, and which caught this exact coupling.
    """
    return os.path.join(ROOT, "backdrops", "source-snapped",
                        "%s-%s" % (loc, fac), "snapped.png")


def door_frame(loc, fac):
    """And where its repaired one does. See `row23_run.DOOR_SOURCE_DIR`."""
    return os.path.join(ROOT, "backdrops", "source-doors",
                        "%s-%s" % (loc, fac), "doored.png")

#: Where the input digests live. Excluded from every input set by construction —
#: see `_is_own` — because a record of what everything was derived from cannot
#: also be one of the things they were derived from: it would move every time
#: anything moved, and nothing could ever settle.
STATE_PATH = os.path.join(HERE, "derived-state.json")

FRESH, STALE, UNPROVEN = "fresh", "stale", "unproven"


# --------------------------------------------------------------- small tools

def rel(p):
    return os.path.relpath(os.path.abspath(p), ROOT)


def sha(p):
    """sha256 of a file, or None where there is no file."""
    if not os.path.exists(p):
        return None
    h = hashlib.sha256()
    with open(p, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _read_json(p, default=None):
    try:
        with open(p) as fh:
            return json.load(fh)
    except (OSError, ValueError):
        return default


def _run(cmd, cwd=None):
    """A generator, run. Returns (ok, output) and never raises on a refusal."""
    r = subprocess.run(cmd, cwd=cwd or ROOT, capture_output=True, text=True,
                       env=dict(os.environ, HOLO_TIMINGS="off"))
    return r.returncode == 0, (r.stdout + r.stderr).strip()


# ------------------------------------------------------------- the input set

#: ONE ARTIFACT MAY BE ANOTHER'S INPUT — a snapped reading is derived, and the
#: material audit genuinely reads it — so the registry is a DAG and not a flat
#: list, and `regenerate` runs to a fixed point. What may never be an input is an
#: artifact's own output (nothing can settle if it is) or the digest record
#: itself.
def _is_own(r, own):
    return r == rel(STATE_PATH) or any(r == o or r.startswith(o + "/") for o in own)


def _expand(patterns, own=()):
    out = set()
    for pat in patterns:
        for p in glob.glob(os.path.join(ROOT, pat), recursive=True):
            if os.path.isfile(p) and not _is_own(rel(p), own):
                out.add(rel(p))
    return sorted(out)


def input_digest(patterns, own=()):
    """One digest over (path, content) for every input, sorted.

    The PATH is hashed beside the bytes so that adding or removing a file moves
    the digest even when the bytes that remain are unchanged — a promotion that
    adds a wall must stale the audit that counts walls.
    """
    h = hashlib.sha256()
    n = 0
    for r in _expand(patterns, own):
        h.update(r.encode("utf-8"))
        h.update(b"\0")
        h.update((sha(os.path.join(ROOT, r)) or "").encode("ascii"))
        h.update(b"\n")
        n += 1
    return h.hexdigest(), n


#: The store, as an input set: the promoted picture and the promoted meta of
#: every wall. Every artifact below that reads the store reads exactly this.
STORE = ["backdrops/*/[NESW].png", "backdrops/*/[NESW].meta.json"]
#: The asks and the readings a promotion resolves back to.
ASKS = ["backdrops/source/*/*.prompt.txt", "backdrops/source-*/*/*.prompt.txt"]
READINGS = ["design/plan-draft/measured/*-[NESW].json",
            "design/plan-draft/measured/row35snap/*.json",
            "design/plan-draft/measured/row36doors/*.json"]


# ------------------------------------------------------------ the witnesses
#
# A WITNESS is a check the artifact can answer about ITSELF, off its own record,
# with nothing regenerated. Where one exists it is the authority and the input
# digest is not consulted: it is exact, it is cheap, and it names the wall.

def _snap_pairs():
    """(key, reading path, frame path, source candidate) for every snapped
    reading in the production round."""
    out = []
    d = os.path.join(HERE, SNAP_ROUND)
    if not os.path.isdir(d):
        return out
    for f in sorted(os.listdir(d)):
        if not f.endswith(".json"):
            continue
        doc = _read_json(os.path.join(d, f))
        if not doc:
            continue
        loc, fac = f[:-5].rsplit("-", 1)
        snap = doc.get("_snap") or {}
        frame = None
        said = str(doc.get("_what_this_is") or "")
        mark = "The image it describes is "
        if mark in said:
            frame = said.split(mark, 1)[1].split(".png", 1)[0] + ".png"
        #: A frame the reading names from OUTSIDE the tree is not a frame this
        #: repository has: the pilot batch and the production round both live
        #: under ROOT, and anything else is a reading written by a run that
        #: staged its output somewhere temporary. Such a reading is re-derived
        #: at the production path rather than followed off the edge of the tree.
        escaped = bool(frame) and (frame.startswith("..") or os.path.isabs(frame))
        out.append({"key": "%s/%s" % (loc, fac), "doc": rel(os.path.join(d, f)),
                    "frame": None if escaped else frame, "escaped": escaped,
                    "production_frame": rel(snap_frame(loc, fac)),
                    "candidate": snap.get("source_candidate"),
                    "recorded": doc.get("_source_sha256")})
    return out


def witness_snap_readings():
    """A snapped reading must describe the frame that is on disk.

    THIS IS THE SEAM ITSELF. `backdrops/source-snapped/<loc>-<F>/snapped.png` is
    keyed by WALL and not by candidate, so a later pass that snaps a newer roll
    of the same wall overwrites the frame a promoted wall was measured on — and
    the reading, the promoted meta and the store's own picture then describe a
    picture that is no longer there. Three walls were in exactly that state when
    this file was written, and `snap.spec`, `assembly.spec` and `fixtures.spec`
    were each red for it in a different language.
    """
    bad = []
    for p in _snap_pairs():
        if p["escaped"]:
            bad.append((p["doc"], "the reading names a frame outside this tree, so "
                                  "nothing here can be the image it describes"))
            continue
        if not p["frame"]:
            bad.append((p["doc"], "the reading does not name the image it describes"))
            continue
        fp = os.path.join(ROOT, p["frame"])
        if not os.path.exists(fp):
            bad.append((p["doc"], "it names %s and there is no such frame" % p["frame"]))
            continue
        got = sha(fp)
        if got != p["recorded"]:
            bad.append((p["doc"],
                        "%s is not the frame this reading was written for "
                        "(records %s, the frame on disk is %s) — the wall was "
                        "re-snapped on another roll and the frame was rewritten "
                        "under the reading"
                        % (p["frame"], (p["recorded"] or "-")[:12], (got or "-")[:12])))
    return bad


def witness_door_readings():
    """A door-void reading must describe the repaired frame that is on disk."""
    bad = []
    d = os.path.join(HERE, DOOR_ROUND)
    if not os.path.isdir(d):
        return bad
    for f in sorted(os.listdir(d)):
        if not f.endswith(".json"):
            continue
        doc = _read_json(os.path.join(d, f)) or {}
        r = doc.get("_doors_repair") or {}
        img = r.get("image")
        if not img:
            bad.append((rel(os.path.join(d, f)),
                        "the reading carries no `_doors_repair.image`, so nothing "
                        "says which frame it describes"))
            continue
        got = sha(os.path.join(ROOT, img))
        if got is None:
            bad.append((rel(os.path.join(d, f)), "it names %s and there is no such frame" % img))
        elif got != doc.get("_source_sha256"):
            bad.append((rel(os.path.join(d, f)),
                        "%s is not the repaired frame this reading was written for" % img))
    return bad


def promoted_walls():
    """(key, meta path, candidate) for every promoted wall in the store."""
    out = []
    b = os.path.join(ROOT, "backdrops")
    for loc in sorted(os.listdir(b)):
        d = os.path.join(b, loc)
        if not os.path.isdir(d) or loc.startswith("source"):
            continue
        for f in "NESW":
            mp = os.path.join(d, "%s.meta.json" % f)
            if not os.path.exists(mp):
                continue
            m = _read_json(mp) or {}
            cand = str(m.get("camera_id") or "").replace("measured:", "") or None
            out.append({"key": "%s/%s" % (loc, f), "meta": rel(mp), "candidate": cand,
                        "png": rel(os.path.join(d, "%s.png" % f)),
                        "round": m.get("measured_round")})
    return out


def witness_promoted_metas():
    """The store's picture is a byte copy of the candidate its meta names, and
    the reading that candidate was measured in describes that candidate.

    This is `fixtures.spec`'s promotion-staleness case made cheap. That case
    re-runs the whole promotion into a staged tree and byte-compares the meta,
    which is the honest check and costs a minute; what it can catch that nothing
    else can is a meta written from a picture that has since been replaced — and
    THAT is answerable from two digests. Where they disagree the promotion has
    to be run again, and this says which wall and why.
    """
    bad = []
    for w in promoted_walls():
        if not w["candidate"]:
            bad.append((w["meta"], "the meta names no candidate at all"))
            continue
        cp = os.path.join(ROOT, w["candidate"])
        if not os.path.exists(cp):
            bad.append((w["meta"], "it names a candidate that is not in the tree: %s"
                        % w["candidate"]))
            continue
        if sha(cp) != sha(os.path.join(ROOT, w["png"])):
            bad.append((w["png"],
                        "the store's picture is not a byte copy of %s, the candidate "
                        "its own meta names — the frame moved after the promotion"
                        % w["candidate"]))
        loc, fac = w["key"].split("/")
        doc = os.path.join(HERE, w["round"] or "", "%s-%s.json" % (loc, fac))
        d = _read_json(doc)
        if d is None:
            bad.append((w["meta"], "its measurement round (%s) holds no reading for it"
                        % (w["round"] or "the top round")))
        elif d.get("_source_sha256") and d["_source_sha256"] != sha(cp):
            bad.append((rel(doc),
                        "the reading %s was promoted from does not describe %s"
                        % (w["key"], w["candidate"])))
    return bad


def _edge_seed_entries():
    doc = _read_json(RETRIES_FILE) or {}
    return [e for e in doc.get("entries", []) if e.get("edge_seed")]


def _seed_rolled(e):
    """Has the packet this strip was cut for already been painted?

    A strip is TWO things at once: the reference image a packet carries, and a
    record of what was handed to the painter. Once a roll has come back the
    strip is evidence and may not be recut — the record would then describe an
    ask nobody made. Before any roll it is only an input, and an input cut from
    a painting the store has replaced is simply wrong.
    """
    for r in e.get("rolls") or []:
        if r.get("candidate") and os.path.exists(os.path.join(ROOT, r["candidate"])):
            return r["candidate"]
    return None


def witness_edge_seeds():
    """Every recorded strip is the strip on disk, cut from the painting on disk.

    `seams.spec` reads this record and re-hashes both files. What breaks it is a
    neighbour's RE-PROMOTION: the strip was cut from `backdrops/<loc>/<F>.png`
    and that wall has since been superseded, so the source digest in the record
    is a digest of bytes that are gone.
    """
    bad = []
    for e in _edge_seed_entries():
        s = e["edge_seed"]
        f = os.path.join(ROOT, s["file"])
        if not os.path.exists(f):
            bad.append((s["file"], "%s's recorded strip is not on disk" % e["key"]))
        elif sha(f) != s.get("sha256"):
            bad.append((s["file"], "%s's strip is not the bytes the record names" % e["key"]))
        src = os.path.join(ROOT, s["source"])
        got = sha(src)
        if got is None:
            bad.append((s["source"], "%s's seed source painting is gone" % e["key"]))
        elif got != s.get("source_sha256"):
            stale = s.get("stale_from") or {}
            if stale.get("source_sha256") == s.get("source_sha256") and \
                    stale.get("now_sha256") == got:
                continue          # recorded, with its reason — see `_regen_edge_seeds`
            bad.append((s["source"],
                        "%s's strip was cut from %s at %s and the store now holds %s "
                        "there — the neighbour was re-promoted under the record"
                        % (e["key"], s["source"], (s.get("source_sha256") or "-")[:12],
                           got[:12])))
    return bad


# ------------------------------------------------------------- the actions
#
# One action per artifact family. Each returns (paths_written, note); it writes
# only where the bytes actually move, so a second run writes nothing and the
# caller can say so.

def _write_if_moved(path, data):
    """Write `data` (bytes) at `path` only if it is not already there."""
    if os.path.exists(path):
        with open(path, "rb") as fh:
            if fh.read() == data:
                return False
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "wb") as fh:
        fh.write(data)
    return True


def _regen_materials(_findings=None):
    """`--audit-materials --seal-legacy`: the provenance report and the ledger.

    `--warn-only` because this is the REGENERATION and not the gate: the gate is
    the same command run without it, and a run that refused to write the report
    describing a store it disapproves of would leave the stale report in place.
    """
    before = {p: sha(p) for p in (
        os.path.join(HERE, "material_provenance.json"),
        os.path.join(HERE, "material_legacy.json"))}
    ok, out = _run(["node", os.path.join(ROOT, "tools", "make-scaffold.mjs"),
                    "--audit-materials", "--seal-legacy", "--warn-only"])
    if not ok:
        return [], "make-scaffold refused: " + out.split("\n")[-1][:200]
    moved = [rel(p) for p, s in before.items() if sha(p) != s]
    return moved, None


def _regen_room_consistency(_findings=None):
    """The per-room measure, and its README — whose hand-written tail is kept by
    `room_consistency.kept_tail`, which is why this runs the tool rather than
    writing the file itself."""
    paths = [os.path.join(HERE, "room_consistency.json"),
             os.path.join(ROOT, "design", "batches", "row40-consistency", "README.md")]
    before = {p: sha(p) for p in paths}
    ok, out = _run(["python3", os.path.join(HERE, "room_consistency.py")])
    if not ok:
        return [], "room_consistency refused: " + out.split("\n")[-1][:200]
    return [rel(p) for p, s in before.items() if sha(p) != s], None


def _regen_window_calibration(_findings=None):
    p = os.path.join(HERE, "window_calibration.json")
    before = sha(p)
    ok, out = _run(["python3", os.path.join(HERE, "window_measure.py"),
                    "--calibrate", "--write", p])
    if not ok:
        return [], "window_measure refused: " + out.split("\n")[-1][:200]
    return ([rel(p)] if sha(p) != before else []), None


def _snap_pair_regen(key, candidate, doc_path, frame_path):
    """Re-derive ONE snapped frame and its reading from the roll the reading
    names. Deterministic — `snap.spec` asserts it — so a pair that is already
    consistent comes back byte-identical and nothing moves.

    THE FRAME IS WRITTEN AT ITS REAL PATH AND NOT STAGED, because the reading
    the snap writes NAMES the file it was told to write ("The image it describes
    is …") and `snap.spec` reads that sentence to find the frame. A first draft
    snapped into a temp directory and copied the two files into place; the copy
    of the reading then named a frame in `/tmp` that no longer existed, which is
    the very defect this artifact exists to prevent, authored by its repair. The
    frame's previous bytes are held instead, and put back if the snap refuses
    part-way — `row35_snap.snap_to_round` writes the picture before the reading,
    so a refusal between the two would otherwise leave exactly the mismatch
    being repaired.
    """
    import row35_snap
    before = None
    if os.path.exists(frame_path):
        with open(frame_path, "rb") as fh:
            before = fh.read()
    tmp = tempfile.mkdtemp(prefix="holo-derive-snap-")
    try:
        out_doc = os.path.join(tmp, "reading.json")
        res, why = row35_snap.snap_to_round(
            key, candidate, round_dir=SNAP_ROUND, out_png=frame_path, doc_out=out_doc)
        if res is None:
            if before is not None:
                _write_if_moved(frame_path, before)
            return [], ("the snap refuses the roll this reading names (%s): %s"
                        % (candidate, why))
        wrote = []
        with open(frame_path, "rb") as fh:
            if fh.read() != before:
                wrote.append(rel(frame_path))
        with open(out_doc, "rb") as fh:
            if _write_if_moved(doc_path, fh.read()):
                wrote.append(rel(doc_path))
        return wrote, None
    except Exception:
        if before is not None:
            _write_if_moved(frame_path, before)
        raise
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def _regen_snap_readings(findings=None):
    """Every snapped pair the witness calls stale, re-derived from its own roll.

    THE READING IS THE RECORD AND THE FRAME IS THE PICTURE. A reading is what an
    instrument measured, it names the roll it was measured on, and the promoted
    meta beside it carries the same numbers; the frame is a warp of that roll and
    can be recomputed exactly. So the frame is brought back to the reading and
    never the other way round. Which roll SHOULD win is the sweep's decision and
    is made of measurements — this only makes the pair describe one picture.
    """
    wrote, notes = [], []
    stale = {p for p, _ in (findings or witness_snap_readings())}
    for p in _snap_pairs():
        if p["doc"] not in stale:
            continue
        if not p["candidate"]:
            notes.append("%s: the reading names no roll to re-derive it from" % p["doc"])
            continue
        if not os.path.exists(os.path.join(ROOT, p["candidate"])):
            notes.append("%s: the roll it names (%s) is not in the tree"
                         % (p["doc"], p["candidate"]))
            continue
        w, why = _snap_pair_regen(p["key"], p["candidate"],
                                  os.path.join(ROOT, p["doc"]),
                                  os.path.join(ROOT, p["frame"] or p["production_frame"]))
        wrote += w
        if why:
            notes.append("%s: %s" % (p["doc"], why))
    return wrote, ("; ".join(notes) or None)


def _regen_door_readings(findings=None):
    """A repaired frame and its reading, re-derived: snap the roll, paint the
    plan's voids onto it, re-read the doors off the result.

    The two halves are `row36_assemble.repair_doors` and `row23_run._doors_
    document`, called in the order the sweep's own void-repair exit calls them,
    because a second implementation of that order is a second answer to which
    document a promotion reads.
    """
    import row23_run
    import row36_assemble
    wrote, notes = [], []
    stale = {p for p, _ in (findings or witness_door_readings())}
    d = os.path.join(HERE, DOOR_ROUND)
    plan = _read_json(PLAN)
    facings = row36_assemble.read_json(row36_assemble.FACINGS)["facings"]
    for f in sorted(os.listdir(d) if os.path.isdir(d) else []):
        if not f.endswith(".json") or rel(os.path.join(d, f)) not in stale:
            continue
        loc, fac = f[:-5].rsplit("-", 1)
        key = "%s/%s" % (loc, fac)
        snap_doc = _read_json(os.path.join(HERE, SNAP_ROUND, f))
        cand = ((snap_doc or {}).get("_snap") or {}).get("source_candidate")
        if not cand:
            notes.append("%s: no snapped reading names the roll this was repaired from" % key)
            continue
        # The snapped half first: the voids are painted onto THAT frame, so a
        # repair over a stale one would carry the stale one forward.
        frame = snap_frame(loc, fac)
        w, why = _snap_pair_regen(key, cand, os.path.join(HERE, SNAP_ROUND, f), frame)
        wrote += w
        if why:
            notes.append("%s: %s" % (key, why))
            continue
        out_png = door_frame(loc, fac)
        tmp = tempfile.mkdtemp(prefix="holo-derive-doors-")
        try:
            staged = os.path.join(tmp, "doored.png")
            rec, why = row36_assemble.repair_doors(key, rel(frame), staged, plan, facings)
            if rec is None:
                notes.append("%s: the door repair refuses this frame: %s" % (key, why))
                continue
            with open(staged, "rb") as fh:
                if _write_if_moved(out_png, fh.read()):
                    wrote.append(rel(out_png))
        finally:
            shutil.rmtree(tmp, ignore_errors=True)
        res = {"candidate": rel(frame), "doc_out": os.path.join(HERE, SNAP_ROUND, f)}
        before = sha(os.path.join(d, f))
        doc_out, why = row23_run._doors_document(key, res, rel(out_png), rec)
        if doc_out is None:
            notes.append("%s: %s" % (key, why))
            continue
        if sha(doc_out) != before:
            wrote.append(rel(doc_out))
    return wrote, ("; ".join(notes) or None)


def _regen_edge_seeds(findings=None):
    """The strip records in `retries.json`, against the store as it stands now.

    TWO OUTCOMES, AND WHICH ONE IS NOT A JUDGEMENT CALL. A packet that has NOT
    been rolled yet is an ask still waiting to go out, so its strip is re-cut
    from the neighbour's current painting and the record is updated — the
    painter must be handed the wall that is in the store. A packet that HAS been
    rolled is history: the strip is what was actually sent, re-cutting it would
    make the record describe an ask nobody made, so the record is marked
    `stale_from` with both digests, the roll that consumed it, and the reason.
    Row 38's claim is about the ask that went out, and that claim stays exactly
    as strong; what changes is that the drift is now written down instead of
    turning a suite case red.
    """
    doc = _read_json(RETRIES_FILE)
    if not doc:
        return [], "there is no retries.json to regenerate"
    wrote, notes, changed = [], [], False
    stale_sources = {p for p, _ in (findings or witness_edge_seeds())}
    for e in doc.get("entries", []):
        s = e.get("edge_seed")
        if not s or s["source"] not in stale_sources:
            continue
        src = os.path.join(ROOT, s["source"])
        now = sha(src)
        if now is None:
            notes.append("%s: its seed source %s is gone from the store"
                         % (e["key"], s["source"]))
            continue
        if now == s.get("source_sha256"):
            continue
        rolled = _seed_rolled(e)
        if rolled:
            s["stale_from"] = {
                "source_sha256": s.get("source_sha256"),
                "now_sha256": now,
                "rolled": rolled,
                "why": ("the strip this packet carried was cut from %s as it stood "
                        "when the ask went out; that neighbour has since been "
                        "re-promoted, and the ask cannot be un-sent. The strip and "
                        "its digest are what was handed to the painter and are left "
                        "exactly as they were." % s["source"]),
                "at": time.strftime("%Y-%m-%dT%H:%M:%S"),
            }
            changed = True
            notes.append("%s: marked stale_from (already rolled as %s)"
                         % (e["key"], os.path.basename(rolled)))
            continue
        # THE SIDE THAT IS CUT IS THE NEIGHBOUR'S, not this wall's: `side` is the
        # edge of THIS picture the strip sits at and `neighbour_edge` is the edge
        # of THAT painting the columns come from. `tools/edge-seed.mjs` passes
        # `plan_.neighbour_edge` for exactly this reason and the re-cut has to
        # ask the same question or it would hand the painter the far side of the
        # room. Same script, same fraction, same positional CLI.
        ok, out = _run(["python3", os.path.join(ROOT, "tools", "crop-edge-seed.py"),
                        s["source"], s["file"], s["neighbour_edge"],
                        str(s.get("fraction", 0.1))])
        if not ok:
            notes.append("%s: the strip could not be re-cut: %s"
                         % (e["key"], out.split("\n")[-1][:160]))
            continue
        s["sha256"] = sha(os.path.join(ROOT, s["file"]))
        s["source_sha256"] = now
        s["recut"] = {"at": time.strftime("%Y-%m-%dT%H:%M:%S"),
                      "why": ("the neighbour was re-promoted before this packet was "
                              "rolled, so the ask carries the painting the store "
                              "actually holds")}
        changed = True
        wrote.append(s["file"])
        notes.append("%s: strip re-cut from the current %s" % (e["key"], s["source"]))
    if changed:
        # `ensure_ascii=False` because the emitter that writes this file is
        # node's `JSON.stringify`, which does not escape a non-ASCII character —
        # and every correction sentence in here carries an em dash. Writing it
        # back the python default way turned a one-line change into a 221-line
        # diff of `—` churn, which is the record made unreadable by the
        # tool that keeps it.
        data = (json.dumps(doc, indent=2, ensure_ascii=False) + "\n").encode("utf-8")
        if _write_if_moved(RETRIES_FILE, data):
            wrote.append(rel(RETRIES_FILE))
    return wrote, ("; ".join(notes) or None)


def bake(root=ROOT):
    """`backdrops/baked.js` and every fixture that reads a promoted meta.

    ONE HOME FOR THE BAKE COMMANDS. `row23_run._bake` is this function with the
    sweep's own stopwatch around it; the publish preflight and `--regen` reach it
    here. A promoted wall changes two baked artifacts and not one — the picture
    and the meta the page renders it with — and baking only the first is how a
    sweep leaves `fixtures/nav-manor/fixture.js` stale.
    """
    out = []
    r = subprocess.run(["node", os.path.join(root, "tools", "bake-backdrops.mjs")],
                       cwd=root, capture_output=True, text=True)
    if r.returncode != 0:
        return 0, "backdrops/baked.js: " + (r.stdout + r.stderr).strip()[-300:]
    n = 0
    for d in sorted(os.listdir(os.path.join(root, "fixtures"))):
        fd = os.path.join(root, "fixtures", d)
        if not os.path.exists(os.path.join(fd, "world.json")):
            continue
        r = subprocess.run(["node", os.path.join(root, "tools", "bake-fixtures.mjs"),
                            "--fixture-dir", fd], cwd=root,
                           capture_output=True, text=True)
        n += 1
        if r.returncode != 0:
            out.append("fixtures/%s: %s" % (d, (r.stdout + r.stderr).strip()[-300:]))
    return n, (out[0] if out else None)


def _regen_bake(_findings=None):
    before = {p: sha(p) for p in
              [os.path.join(ROOT, "backdrops", "baked.js")] +
              glob.glob(os.path.join(ROOT, "fixtures", "*", "fixture.js"))}
    _n, bad = bake()
    if bad:
        return [], bad
    now = set(glob.glob(os.path.join(ROOT, "fixtures", "*", "fixture.js")))
    now.add(os.path.join(ROOT, "backdrops", "baked.js"))
    return [rel(p) for p in sorted(now) if sha(p) != before.get(p)], None


# ------------------------------------------------------------- the deep check

def _deep_cmp(paths, run_into):
    """Regenerate into a temp directory and byte-compare. `run_into(tmp)` returns
    a dict of {committed path -> the temp file that should equal it}."""
    tmp = tempfile.mkdtemp(prefix="holo-derive-deep-")
    try:
        pairs, why = run_into(tmp)
        if why:
            return [(paths[0], why)]
        bad = []
        for committed, fresh in pairs.items():
            a = os.path.join(ROOT, committed)
            if not os.path.exists(fresh):
                bad.append((committed, "a fresh run wrote nothing to compare against"))
            elif not os.path.exists(a) or open(a, "rb").read() != open(fresh, "rb").read():
                bad.append((committed, "a fresh run of its generator writes different bytes"))
        return bad
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def _deep_materials(paths):
    def go(tmp):
        mp, lp = os.path.join(tmp, "mp.json"), os.path.join(tmp, "ml.json")
        ok, out = _run(["node", os.path.join(ROOT, "tools", "make-scaffold.mjs"),
                        "--audit-materials", "--seal-legacy", "--warn-only",
                        "--out", mp, "--legacy-out", lp])
        if not ok:
            return None, "make-scaffold refused: " + out.split("\n")[-1][:200]
        return {"design/plan-draft/measured/material_provenance.json": mp,
                "design/plan-draft/measured/material_legacy.json": lp}, None
    return _deep_cmp(paths, go)


def _deep_room_consistency(paths):
    def go(tmp):
        j, m = os.path.join(tmp, "rc.json"), os.path.join(tmp, "README.md")
        # The README's hand-written tail is kept from the committed file, which
        # is what the tool does on the real path too — so what is compared is
        # the generated half and not the human's account.
        import room_consistency
        tail = room_consistency.kept_tail(
            os.path.join(ROOT, "design", "batches", "row40-consistency", "README.md"))
        with open(m, "w") as fh:
            fh.write(tail.lstrip("\n"))
        ok, out = _run(["python3", os.path.join(HERE, "room_consistency.py"),
                        "--json", j, "--md", m])
        if not ok:
            return None, "room_consistency refused: " + out.split("\n")[-1][:200]
        return {"design/plan-draft/measured/room_consistency.json": j,
                "design/batches/row40-consistency/README.md": m}, None
    return _deep_cmp(paths, go)


def _deep_window_calibration(paths):
    def go(tmp):
        w = os.path.join(tmp, "wc.json")
        ok, out = _run(["python3", os.path.join(HERE, "window_measure.py"),
                        "--calibrate", "--write", w])
        if not ok:
            return None, "window_measure refused: " + out.split("\n")[-1][:200]
        return {"design/plan-draft/measured/window_calibration.json": w}, None
    return _deep_cmp(paths, go)


def _deep_bake(paths):
    def go(tmp):
        pairs = {}
        out = os.path.join(tmp, "baked.js")
        ok, msg = _run(["node", os.path.join(ROOT, "tools", "bake-backdrops.mjs"),
                        "--out", out])
        if not ok:
            return None, "the backdrop bake refused: " + msg.split("\n")[-1][:200]
        pairs["backdrops/baked.js"] = out
        for fd in sorted(glob.glob(os.path.join(ROOT, "fixtures", "*", "world.json"))):
            d = os.path.dirname(fd)
            o = os.path.join(tmp, os.path.basename(d) + ".fixture.js")
            ok, msg = _run(["node", os.path.join(ROOT, "tools", "bake-fixtures.mjs"),
                            "--fixture-dir", d, "--out", o])
            if not ok:
                return None, "fixtures/%s bake refused: %s" % (os.path.basename(d),
                                                               msg.split("\n")[-1][:200])
            pairs[rel(os.path.join(d, "fixture.js"))] = o
        return pairs, None
    return _deep_cmp(paths, go)


# ---------------------------------------------------------------- the registry

ARTIFACTS = [
    {
        "id": "snap_readings",
        "paths": ["design/plan-draft/measured/row35snap"],
        "invalidated_by": "a re-snap: the frame is keyed by WALL, so snapping "
                          "another roll of the same wall rewrites the picture "
                          "the reading describes",
        "witness": witness_snap_readings, "action": "snap_readings",
        "regen": "python3 design/plan-draft/measured/derived.py --regen --only snap_readings",
    },
    {
        "id": "door_readings",
        "paths": ["design/plan-draft/measured/row36doors"],
        "invalidated_by": "a re-repair, or a change to the snapped frame the "
                          "voids were painted onto",
        "witness": witness_door_readings, "action": "door_readings",
        "regen": "python3 design/plan-draft/measured/derived.py --regen --only door_readings",
    },
    {
        "id": "edge_seed_records",
        "paths": ["design/batches/row23-scaffold/manor/retries.json"],
        "invalidated_by": "a neighbour's re-promotion: the strip was cut from a "
                          "painting the store has since replaced",
        "witness": witness_edge_seeds, "action": "edge_seeds",
        "regen": "python3 design/plan-draft/measured/derived.py --regen --only edge_seed_records",
    },
    {
        "id": "promoted_metas",
        "paths": ["backdrops"],
        "invalidated_by": "the candidate a meta names being replaced under it",
        "witness": witness_promoted_metas, "action": None,
        "regen": "python3 design/plan-draft/measured/row23_run.py --derive-check "
                 "names the wall; the promotion itself is the sweep's act",
    },
    {
        "id": "material_provenance",
        "paths": ["design/plan-draft/measured/material_provenance.json"],
        "invalidated_by": "any promotion or supersede; any edit to the voice "
                          "table or to the material composer",
        "inputs": STORE + ASKS + READINGS + [
            "design/batches/row23-scaffold/manor/run-state.json",
            "fixtures/demo-study/plan.json", "tools/room-voices.mjs",
            "tools/make-scaffold.mjs", "tools/flight-evidence.mjs",
            "tools/plan-projection.mjs"],
        "action": "materials", "deep": _deep_materials,
        "regen": "node tools/make-scaffold.mjs --audit-materials --seal-legacy",
    },
    {
        "id": "material_legacy",
        "paths": ["design/plan-draft/measured/material_legacy.json"],
        "invalidated_by": "any promotion or supersede: an entry admits one facing "
                          "from one exact candidate, so a re-ask closes a line",
        "inputs": STORE + ASKS + READINGS + [
            "design/batches/row23-scaffold/manor/run-state.json",
            "fixtures/demo-study/plan.json", "tools/room-voices.mjs",
            "tools/make-scaffold.mjs", "tools/flight-evidence.mjs",
            "tools/plan-projection.mjs"],
        "action": "materials", "deep": _deep_materials,
        "regen": "node tools/make-scaffold.mjs --audit-materials --seal-legacy",
    },
    {
        "id": "room_consistency",
        "paths": ["design/plan-draft/measured/room_consistency.json"],
        "invalidated_by": "any promotion or supersede in a measured room",
        "inputs": STORE + ["design/plan-draft/measured/room_consistency.py",
                           "design/batches/row23-scaffold/manor/retries.json"],
        "action": "room_consistency", "deep": _deep_room_consistency,
        "regen": "python3 design/plan-draft/measured/room_consistency.py",
    },
    {
        "id": "room_consistency_readme",
        "paths": ["design/batches/row40-consistency/README.md"],
        "invalidated_by": "the same measure; its hand-written tail below the "
                          "first horizontal rule is kept across every run",
        "inputs": STORE + ["design/plan-draft/measured/room_consistency.py",
                           "design/batches/row23-scaffold/manor/retries.json"],
        "action": "room_consistency", "deep": _deep_room_consistency,
        "regen": "python3 design/plan-draft/measured/room_consistency.py",
    },
    {
        "id": "window_calibration",
        "paths": ["design/plan-draft/measured/window_calibration.json"],
        "invalidated_by": "any promotion or supersede — it is the list of "
                          "promoted walls the window clause cannot yet see",
        "inputs": STORE + ["design/plan-draft/measured/window_measure.py",
                           "design/plan-draft/measured/measure_lib.py",
                           "fixtures/demo-study/plan.json"],
        "action": "window_calibration", "deep": _deep_window_calibration,
        "regen": "python3 design/plan-draft/measured/window_measure.py --calibrate "
                 "--write design/plan-draft/measured/window_calibration.json",
    },
    {
        "id": "baked",
        "paths": ["backdrops/baked.js"],
        "invalidated_by": "any promotion: the picture and the meta the page renders",
        "inputs": STORE + ["fixtures/*/world.json", "fixtures/*/staging.json",
                           "tools/bake-backdrops.mjs", "tools/bake-fixtures.mjs"],
        "action": "bake", "deep": _deep_bake,
        "regen": "node tools/bake-backdrops.mjs && node tools/bake-fixtures.mjs "
                 "--fixture-dir fixtures/<world>",
    },
]

#: id -> the callable that remakes it. Several artifacts share one action; an
#: action runs once however many of its artifacts are stale.
ACTIONS = {
    "materials": _regen_materials,
    "room_consistency": _regen_room_consistency,
    "window_calibration": _regen_window_calibration,
    "snap_readings": _regen_snap_readings,
    "door_readings": _regen_door_readings,
    "edge_seeds": _regen_edge_seeds,
    "bake": _regen_bake,
}

#: The registry is ordered: an artifact that is another's input comes first, so
#: one pass of `regenerate` settles the ordinary case and the fixed-point loop
#: is a belt rather than the braces.
BY_ID = {a["id"]: a for a in ARTIFACTS}


# ------------------------------------------------------------------ the check

def _state():
    return _read_json(STATE_PATH, {}) or {}


def check(only=None, deep=False):
    """What is stale, and why. Writes nothing. Returns a list of records."""
    st = _state().get("artifacts", {})
    out = []
    for a in ARTIFACTS:
        if only and a["id"] != only:
            continue
        rec = {"id": a["id"], "paths": a["paths"],
               "invalidated_by": a["invalidated_by"], "regen": a["regen"],
               "state": FRESH, "why": []}
        missing = [p for p in a["paths"] if not os.path.exists(os.path.join(ROOT, p))]
        if missing:
            rec["state"] = STALE
            rec["why"] = [(p, "it has never been written") for p in missing]
            out.append(rec)
            continue
        if a.get("witness"):
            bad = a["witness"]()
            if bad:
                rec["state"] = STALE
                rec["why"] = bad
        else:
            digest, n = input_digest(a["inputs"], a["paths"])
            rec["inputs"] = n
            was = (st.get(a["id"]) or {}).get("input_digest")
            if was is None:
                rec["state"] = UNPROVEN
                rec["why"] = [(a["paths"][0],
                               "nothing records what this was last derived from, "
                               "so it cannot be shown fresh — run the regen once")]
            elif was != digest:
                rec["state"] = STALE
                rec["why"] = [(a["paths"][0],
                               "its inputs have moved since it was last derived "
                               "(%d inputs; %s -> %s)" % (n, was[:12], digest[:12]))]
        if deep and a.get("deep"):
            bad = a["deep"](a["paths"])
            rec["deep"] = "stale" if bad else "fresh"
            if bad and rec["state"] == FRESH:
                rec["state"] = STALE
                rec["why"] = [(p, w + " — and the fast check called it fresh, "
                               "which is a defect in this file's input set") for p, w in bad]
            elif bad:
                rec["why"] += bad
            elif not bad and rec["state"] == STALE and not a.get("witness"):
                rec["why"].append((a["paths"][0],
                                   "NOTE: a fresh run writes the same bytes; the "
                                   "input digest is merely unrecorded for these inputs"))
        out.append(rec)
    return out


def is_stale(records):
    return [r for r in records if r["state"] != FRESH]


# ------------------------------------------------------------------ the regen

#: One artifact is another's input, so regenerating the first stales the second
#: — the snapped readings feed the material audit, the strip records feed the
#: room measure. The registry is ordered upstream-first so one pass settles it;
#: this loop is what makes that an assertion rather than a hope, and it is
#: bounded because a cycle would otherwise be a hang.
MAX_ROUNDS = 4


def regenerate(only=None, verbose=True):
    """Regenerate exactly what the check calls stale, once per action.

    Returns `(records, wrote, notes)`. Each action is clocked as `derive.regen`
    with the artifact it was run for and what it wrote, so the row-33 ledger can
    say what a sweep's derivation cost.

    IDEMPOTENT BY CONSTRUCTION, at two levels: nothing runs whose artifacts the
    check calls fresh, and every action writes through `_write_if_moved`, so an
    action that runs anyway (because one of a shared pair was stale) still moves
    no bytes it does not have to.
    """
    first = check(only=only)
    wrote_all, notes = [], []
    for _round in range(MAX_ROUNDS):
        records = first if _round == 0 else check(only=only)
        stale = is_stale(records)
        if not stale:
            break
        done = set()
        moved = False
        for r in stale:
            a = BY_ID[r["id"]]
            act = a.get("action")
            if act is None:
                notes.append("%s: %s" % (r["id"], r["regen"]))
                continue
            if act in done:
                continue
            done.add(act)
            t0 = time.time()
            wrote, why = ACTIONS[act](r["why"] if a.get("witness") else None)
            # REFUSED MEANS NOTHING WAS WRITTEN AND THE TOOL SAID WHY. An action
            # also returns a NOTE where it did the work in the second of its two
            # licensed ways — the strip record marked `stale_from` rather than
            # re-cut — and a first draft flagged that as a refusal, which would
            # have put a successful derivation in the ledger's failure column.
            timings.record("derive.regen", t0, time.time(), r["id"],
                           {"action": act, "wrote": wrote[:12], "files": len(wrote),
                            "refused": bool(why) and not wrote,
                            "note": (why or "")[:300] or None})
            wrote_all += wrote
            moved = moved or bool(wrote)
            if why:
                notes.append("%s: %s" % (r["id"], why))
            if verbose:
                print("  %-24s %s" % (r["id"], ", ".join(wrote) if wrote else
                                      (why or "nothing moved")))
        _record_state(only=only)
        if not moved:
            break
    return first, wrote_all, notes


def _record_state(only=None):
    """What each artifact was last derived from. See STATE_PATH."""
    st = _state()
    arts = st.setdefault("artifacts", {})
    st["_what_this_is"] = (
        "What every derived artifact was last regenerated FROM, written by "
        "design/plan-draft/measured/derived.py. `--check` recomputes each input "
        "digest and reports an artifact whose inputs have moved. Do not hand-edit: "
        "an entry here is a claim that the artifact beside it was written from "
        "exactly these bytes.")
    for a in ARTIFACTS:
        if only and a["id"] != only:
            continue
        if a.get("witness") or not a.get("inputs"):
            continue
        digest, n = input_digest(a["inputs"], a["paths"])
        arts[a["id"]] = {"input_digest": digest, "inputs": n,
                         "artifacts": {p: sha(os.path.join(ROOT, p)) for p in a["paths"]},
                         "at": time.strftime("%Y-%m-%dT%H:%M:%S")}
    _write_if_moved(STATE_PATH, (json.dumps(st, indent=2, sort_keys=True) + "\n").encode())


# --------------------------------------------------------------------- the CLI

def _print(records):
    for r in records:
        mark = {FRESH: "fresh ", STALE: "STALE ", UNPROVEN: "UNPROVEN"}[r["state"]]
        print("%s %-24s %s" % (mark, r["id"], ", ".join(r["paths"])))
        for p, w in r["why"]:
            print("         %s: %s" % (p, w))
        if r["state"] != FRESH:
            print("         remake: %s" % r["regen"])


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="report what is stale and write nothing (exit 1 if any)")
    ap.add_argument("--regen", action="store_true", help="remake what is stale")
    ap.add_argument("--deep", action="store_true",
                    help="with --check: regenerate into a temp tree and byte-compare")
    ap.add_argument("--only", default=None, help="one artifact id")
    ap.add_argument("--json", action="store_true", help="machine-readable")
    ap.add_argument("--table", action="store_true",
                    help="print the artifact -> invalidator table and stop")
    a = ap.parse_args()

    if a.table:
        print("%-24s %-44s %s" % ("artifact", "paths", "invalidated by"))
        for x in ARTIFACTS:
            print("%-24s %-44s %s" % (x["id"], ", ".join(x["paths"]), x["invalidated_by"]))
        return 0

    if a.regen:
        records, wrote, notes = regenerate(only=a.only)
        if not is_stale(records):
            print("nothing to regenerate: every derived artifact is already "
                  "what its inputs say it should be")
        for n in notes:
            print("  !! %s" % n)
        if wrote:
            print("wrote %d file(s)" % len(wrote))
        after = check(only=a.only)
        if is_stale(after):
            print("\nSTILL STALE after the regen:")
            _print(is_stale(after))
            return 1
        return 0

    records = check(only=a.only, deep=a.deep)
    if a.json:
        print(json.dumps({"artifacts": records,
                          "stale": [r["id"] for r in is_stale(records)]}, indent=2))
    else:
        _print(records)
        bad = is_stale(records)
        print("\n%d of %d derived artifact(s) are stale against the store."
              % (len(bad), len(records)))
        if bad:
            print("Run: python3 design/plan-draft/measured/derived.py --regen")
    return 1 if is_stale(records) else 0


if __name__ == "__main__":
    sys.exit(main())
