// GENERATED by tools/bake-worlds-index.mjs — the packs whose visitor world is baked.
window.HOLO_WORLDS = [
 {
  "id": "cyberpunk-2",
  "title": "KOWLOON-7 STREET LEVEL"
 },
 {
  "id": "hospital-3",
  "title": "ST. BRENDAN'S OUT-PATIENTS WING"
 },
 {
  "id": "nav-manor",
  "title": "A circa-1660 English manor"
 },
 {
  "id": "underground-2",
  "title": "BRUNSWICK HALT 1931"
 }
];
